name: Daily Morning Tweet

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    # Runs at 23:00 UTC every day (8:00 AM JST)
    - cron: '0 23 * * *'

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create Google Credentials file from Secret
        env:
          GS_CREDENTIALS_FILE_CONTENT: ${{ secrets.GS_CREDENTIALS_FILE_CONTENT }}
        run: |
          echo "$GS_CREDENTIALS_FILE_CONTENT" > google-credentials.json

      - name: Run Tweet Poster
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET_KEY: ${{ secrets.X_API_SECRET_KEY }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GS_CREDENTIALS_FILE_PATH: ./google-credentials.json # Path for the script to find the credentials
          PYTHONIOENCODING: "utf-8"
        run: python x_poster/morning_greet_poster.py

# This is a test comment to trigger re-scan
