name: 'Debug Action - Test'

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Run a one-line script'
        run: echo "Hello, world! Testing with a previously successful filename."
