name: Tweet Job

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  post_tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - name: Create credentials file
        env:
          GS_CREDENTIALS_FILE_CONTENT: ${{ secrets.GS_CREDENTIALS_FILE_CONTENT }}
        run: echo "$GS_CREDENTIALS_FILE_CONTENT" > google-credentials.json
      - name: Run tweet script
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET_KEY: ${{ secrets.X_API_SECRET_KEY }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GS_CREDENTIALS_FILE_PATH: ./google-credentials.json
          PYTHONIOENCODING: "utf-8"
        run: python x_poster/morning_greet_poster.py
